language: r
dist: trusty
sudo: false


r_packages:
   - data.table
   - RefManageR
   - DT
   - kableExtra
   - blogdown
   
branches:
  only:
    - source

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - Rscript -e 'blogdown::install_hugo(version="0.30")'

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: source
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master  
  local_dir: public

#fqdn: travis-blogdown.yihui.name
